### PR TITLE
Optimizely X summary schema

### PR DESCRIPTION
**Pull request by miike**
Adds the Optimizely X summary schema. Companion PR to https://github.com/snowplow/snowplow-javascript-tracker/pull/552

### CODE REVIEW

**Comment by snowplowcla** [comment]
@miike has signed the Software Grant and Corporate Contributor License Agreement

**Comment by BenFradet** [comment]
@alexanderdean getting this on your radar since this is needed for the js tracker release.

**Comment by alexanderdean** [comment]
Assuming this is fine but just getting reviewers to say so...

**Comment by alexanderdean** [comment]
Hmm. I wonder if we should rename this to:

    com.optimizely.optimizelyx/summary/jsonschema/1-0-0 

This feels cleaner (separate namespace for the OptimizelyX product)...

Thoughts?

**Comment by miike** [comment]
I think this comes down to

>Does the product for an event belong in the vendor field or the event field?

I don't think there's necessarily a correct answer but I'd agree and lean towards including it in the vendor field rather than the event name - even if this makes it something closer to a namespace rather than strictly a vendor.

**Comment by alexanderdean** [comment]
Makes sense @miike - I will move the schema into `com.optimizely.optimizelyx`. You are right, we use this field more as a namespace than as a strict vendor (see e.g. all the `com.snowplowanalytics.` folders in Iglu Central)...

**Comment by miike** [comment]
I've modified this PR to move the event name from `optimizelyx_summary` to `summary` and event vendor from `com.optimizely` to `com.optimizely.optimizelyx`. I've also updated the companion PR to reflect this path change https://github.com/snowplow/snowplow-javascript-tracker/pull/567

**Comment by BenFradet** [comment]
@miike integrated your changes in snowplow/snowplow-javascript-tracker#562

**Comment by alexanderdean** [comment]
Thanks @miike , thanks @BenFradet ! This Iglu Central release is going out today :ship:

**Comment by alexanderdean** [comment]
Split into three commits and cherry-picked into #544

**Pull request closed without merging**
