### PR TITLE
R114

### PR DESCRIPTION
**Pull request by peel**
Regex filtering in recovery config

### CODE REVIEW

**Comment by chuwy** [comment]
The patch is safe because `2-0-0` has never been used anywhere and recovery job 0.2.0 is not released yet. @colmsnowplow, @jbeemster could you please have a look.

**Comment by jbeemster** [comment]
If this has never been used anywhere presumably it would also be fairly simple to just increment the schema version to avoid patching?

**Comment by chuwy** [comment]
> it would also be fairly simple to just increment the schema version to avoid patching?
That's true. I think we should make this a rule a thumb to create patches only when there's no other way to fix production software.

@peel could you please rework this into `3-0-0`? We should just abandon `2-0-0`

**Comment by peel** [comment]
@chuwy Done

**Comment by chuwy** [comment]
Fixed the CHANGELOG entry. 

@jbeemster I think its ready now.

**Comment by peel** [comment]
Hey guys, what's the plan on this one? Can it be released?

**Pull request merged**
