### PR TITLE
Webhooks/sendgrid

### PR DESCRIPTION
**Pull request by ninjabear**

### CODE REVIEW

**Comment by alexanderdean** [comment]
This looks good to me! Note that when we do the CHANGELOG and release, we should be referring to `com.sendgrid/processed/jsonschema/1-0-0` not `com.sendgrid/processed`

**Comment by ninjabear** [comment]
@alexanderdean hopefully that's what you were saying? I also properly nested all the files under a jsonschema directory which I hadn't noticed is what the others do

**Comment by alexanderdean** [comment]
That's the one - thanks @ninjabear !

**Comment by alexanderdean** [comment]
"additionalProperties" should be true unless we are guaranteeing that no additional properties could be added by SendGrid (all per HipChat discussion)

**Comment by ninjabear** [comment]
@alexanderdean do you think this should include sub trees? [Example](https://gist.github.com/ninjabear/c7b1ab3525d1bb60e9c7#file-deferred_schema_with_optionals-json-L35)

I've set them all to true for now, as I think the same problems with setting it to false probably apply to sub items

**Comment by alexanderdean** [comment]
Sorry for delay in responding - *yes* I think we should allow additionalProperties in sub-trees.

**Comment by alexanderdean** [comment]
Closing this now we have a draft branch (releases/r64).

**Pull request closed without merging**
