### PR TITLE
Release/r88

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Thanks @chuwy - please add Mike's PR into this one too...

**Comment by alexanderdean** [comment]
Please obviously update the Iglu Central milestones in GH too so they match up with this PR.

**Comment by chuwy** [comment]
Hey @alexanderdean, this is ready now.

**Comment by alexanderdean** [comment]
@chuwy can you take a look through @mhadam's notification event schema? Just looking for anything unusual. I don't expect any domain knowledge from you on the event itself.

**Comment by chuwy** [comment]
Hey @mhadam! https://github.com/snowplow/iglu-central/pull/743/commits/2548d905c1843b99abbbcddc8a02c0a33d471c99 looks good to me, however I'm wondering if it is possible to add some `maxLength` to strings? Problem is that they're still bounded in Redshift, but implicitly by 4096, which is not optimal value in most cases. Also few `description`s will also be useful.

**Comment by chuwy** [comment]
Thanks for update @mhadam. @alexanderdean this PR is ready.

**Pull request merged**
