### PR TITLE
R92

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by chuwy** [comment]
Hey @alexanderdean, this is ready with only one patch and today release date.

**Comment by jbeemster** [comment]
Hey @chuwy - why is there only task_update and not job_update as was in the original PR?

**Comment by chuwy** [comment]
Oh, wow. Thanks @jbeemster, my bad I've missed it!

**Comment by jbeemster** [comment]
No worries!

**Comment by chuwy** [comment]
Fixed.

**Pull request merged**
