### PR TITLE
Add schemas for header extractor enrichment

### PR DESCRIPTION
**Pull request by khalidjaz**
Implementing https://github.com/snowplow/snowplow/issues/1373

### CODE REVIEW

**Comment by alexanderdean** [comment]
Cool! Looking forward to the Snowplow PR...

**Comment by kazjote** [comment]
Can we have it merged and deployed to iglu-central soon? We could than deploy Headers Enrichment with custom jar based on https://github.com/snowplow/snowplow/pull/2421 without deploying custom iglu repository.

**Comment by chuwy** [comment]
@khalidjaz please fix indentation in properties.name.type too.

**Comment by khalidjaz** [comment]
@chuwy Done, also squashed them into one commit, Thanks!

**Comment by chuwy** [comment]
Thank you very much @kazjote

**Comment by alexanderdean** [comment]
Closing in favour of #302

**Comment by alexanderdean** [comment]
@khalidjaz, @kazjote - this is live in Iglu Central. But please note the slight changes in the schema URIs (you will need to update the PR into snowplow/snowplow accordingly).

**Pull request closed without merging**
