### PR TITLE
Patch snowflake config

### PR DESCRIPTION
**Pull request by chuwy**
I don't believe this config used anywhere except my code - therefore this is patch.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Should we also tolerate null for those two fields, in case somebody wants to send in a JSON config with those values nulled (easier when rendering from a template)?

**Comment by chuwy** [comment]
@alexanderdean agree.

**Comment by chuwy** [comment]
Done. @knservis could you please cherry-pick it into your branch and close this PR?

**Comment by alexanderdean** [comment]
Assigning to Kostas to handle.

**Comment by chuwy** [comment]
Superseded by https://github.com/snowplow/iglu-central/pull/672

**Comment by alexanderdean** [comment]
Removing from schedule

**Pull request closed without merging**
