### PR TITLE
Add com.snowplowanalytics.dataflowrunner/PlaybookConfig/avro/1-0-1

### PR DESCRIPTION
**Pull request by BenFradet**
Added tags to the playbook config, cf snowplow/dataflow-runner#27

### CODE REVIEW

**Comment by alexanderdean** [comment]
Hey @BenFradet - can you remind me why this is a revision (1-1-0) and not an additive change (1-0-1)? A revision means a widening of an existing type, such that an existing reader might break...

**Comment by BenFradet** [comment]
Then #515 should have been 1-0-1 :/

**Comment by BenFradet** [comment]
@alexanderdean updated

**Comment by alexanderdean** [comment]
Oh! My bad for not catching that other one...

**Comment by alexanderdean** [comment]
Cherry-picked into release branch. Closing

**Pull request closed without merging**
