### PR TITLE
Release 85

### LINKED ISSUE #710: Placeholder for sorting out the R84 missing JSON Paths and SQL files
Iglu R84 is missing all of the JSON Paths files, and all of the SQL files, for the GA adapter.

No idea how this got missed by everybody, including me.

This is a blocker on the release of the GA adapter.

### PR DESCRIPTION
**Pull request by dilyand**

### CODE REVIEW

**Comment by dilyand** [comment]
Ah, yes, because they have a different vendor. Added them now.

**Comment by BenFradet** [comment]
Took advantage of this branch to fix #709

**Comment by alexanderdean** [comment]
Many thanks both,

@dilyand - I've split the placeholder into 6 tickets, #712, #713, #714, #715, #716, #717. Please can you split your 2 commits into 6 commits per the above.

@BenFradet - once Dilyan has done this, please do the `Prepare for release` commit (include CHANGELOG) with Tuesday's date.

**Comment by dilyand** [comment]
Done on my end.

**Comment by BenFradet** [comment]
Thanks @dilyand , took care of the prepared for rel commit as well 👍

**Pull request merged**
