### PR TITLE
R97

### PR DESCRIPTION
**Pull request by chuwy**

### CODE REVIEW

**Comment by alexanderdean** [comment]
Is this ready for me to review @chuwy ?

**Comment by chuwy** [comment]
It is now.

**Comment by chuwy** [comment]
@alexanderdean  just updated the release date, in case you will have time to publish it today/tomorrow.

**Comment by chuwy** [comment]
Thanks @alexanderdean, I've addressed your feedback and update the date in CHANGELOG to 2nd of October.

**Comment by jethron** [comment]
Any ETA on this guys?

**Comment by alexanderdean** [comment]
This PR is safe to merge because the RDB Loader uses `TRUNCATECOLUMNS` when loading the shredded tables:

https://github.com/snowplow/snowplow-rdb-loader/blob/master/src/main/scala/com/snowplowanalytics/snowplow/rdbloader/loaders/RedshiftLoadStatements.scala#L212

(without this, the widening of the Id fields in the JSON Schema would immediately cause Redshift loads to break).

**Pull request merged**
