### PR TITLE
Added SCHEMA creation query

### PR DESCRIPTION
**Pull request by ssheikholeslami**
Added a line for creating schema to prevent probable failures, and to make this set of queries like the other sets.

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: **Please visit https://github.com/snowplow/snowplow/wiki/CLA to learn more and sign.**

Once you've signed, please reply here (e.g. `I signed it!`) and we'll verify. Thanks.

**Comment by ssheikholeslami** [comment]
I Signed it :P

**Comment by snowplowcla** [comment]
Confirmed! @ssheikholeslami has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
Scheduling into R69

**Comment by alexanderdean** [comment]
Missed, pushing back

**Comment by alexanderdean** [comment]
Cherry-picked into R70 release branch, closing!

**Pull request closed without merging**
