### PR TITLE
Bq loader bad rows

### PR DESCRIPTION
**Pull request by aldemirenes**

### CODE REVIEW

**Comment by aldemirenes** [comment]
Since I am using `loader_parsing_error schema` in the BQ Loader too, I thought it would be better to starting from Snowflake bad row branch. However, since I've made some changes on the Snowflake bad row branch in forked repo, Snowflake bad row commits is visible as diff in this PR. @chuwy If it is okay, could you push [this branch](https://github.com/aldemirenes/iglu-central/tree/snowflake-badrows) to Snowplow Iglu Central repo as `snowflake-badrows` branch ? After this, only commit in this PR will be the ones related with BQ Loader.

**Comment by aldemirenes** [comment]
Also, I will add descriptions to necessary places in the schemas.

**Comment by chuwy** [comment]
@aldemirenes could you please remove old commits and split `Add BQ Loader bad rows schemas` to commits with its respective tickets?

**Comment by aldemirenes** [comment]
Hey @yali and @chuwy! I ended up with these schemas for BQ Loader bad rows. Could you take a look at it when you are available ?

**Comment by chuwy** [comment]
FYI, @aldemirenes, #987 went into #996 as its necessary for RDB Loader R31, so can be removed from this PR.

**Comment by benjben** [comment]
I updated BQ schemas with this PR https://github.com/aldemirenes/iglu-central/pull/1/commits/16eeb7371092e5b260941f95f9e4e655fec15ffc

I didn't rebase and `fixup` in case it breaks something unexpected.

**Comment by benjben** [comment]
I rebased only to remove `loader_runtime_error 1-0-1`,  because it's now there https://github.com/snowplow/iglu-central/pull/882

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/iglu-central/pull/1013

**Pull request closed without merging**
