### PR TITLE
fix: add Desktop App agentClass

### PR DESCRIPTION
**Pull request by mdimercurio**
Electron applications are not supported by the current schema.

This PR adds support by adding `Desktop App` to the list of valid `agentClass`.

Example user agent sent by our electron app:
```
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_3) AppleWebKit/537.36 (KHTML, like Gecko) CarePlatform/1.91.1-beta.0 Chrome/87.0.4280.141 Electron/11.3.0 Safari/537.36
```
Validated through: https://try.yauaa.basjes.nl/

### CODE REVIEW

**Comment by snowplowcla** [comment]
Thanks for your pull request. Is this your first contribution to a Snowplow open source project? Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

:memo: Please visit https://docs.snowplowanalytics.com/docs/contributing/contributor-license-agreement/ to learn more and sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

**Comment by mdimercurio** [comment]
I signed the CLA

**Comment by snowplowcla** [comment]
Confirmed! @mdimercurio has signed the Contributor License Agreement. Thanks so much.

**Comment by paulboocock** [comment]
Thanks for your PR @mdimercurio 

We will raise this in our next delivery meeting (next Tuesday) and get back to you with regards to merging this.

**Comment by paulboocock** [comment]
Hi @mdimercurio 
We are bumping the YAUAA library in the next version of [Enrich (1.5.0)](https://github.com/snowplow/enrich), which brings a number of updates. We have captured this change, and the other required changes in https://github.com/snowplow/iglu-central/issues/1107 and the corresponding PR https://github.com/snowplow/iglu-central/pull/1108. 

Again, thank you for your contribution 😊

**Pull request closed without merging**
