### PR TITLE
Adding "none" for network type

### PR DESCRIPTION
**Pull request by duncan**
While implementing this in ObjC, I realized that there are times when events will get generated when there's no network connection. Ergo, we need a none. 

I'm not quite sure how to attach a new PR to a closed one that's part of a Milestone—so this one seems have bundled up the full set of changes.

### CODE REVIEW

**Comment by alexanderdean** [comment]
Ah - good point. I'll add in null as well in case there are any mobile devices where we're not allowed to check the connection.

**Comment by alexanderdean** [comment]
Actually I'll leave null out as we are using absence-from-required-fields to indicate null-support in this schema...

**Comment by duncan** [comment]
Ah. That'll work.

**Comment by alexanderdean** [comment]
Hey @duncan - I think maybe we got crossed wires on this one. Did you want to keep "none" as a flag value meaning that there is currently no network connection? (Versus null meaning "we don't know".) It's fine if you do.

**Comment by duncan** [comment]
Maybe an offline would be better?

**Comment by alexanderdean** [comment]
Agree - "offline" sounds good...

**Pull request closed without merging**
