### PR TITLE
Add com.snowplowanalytics.iglu/validation_info/jsonschema/1-0-0

### PR DESCRIPTION
**Pull request by spenes**
Details in https://github.com/snowplow/iglu-central/issues/1285

### CODE REVIEW

**Comment by istreeter** [comment]
For me and for others, please can you help give a concrete example of how this will be used.  For example....

- Enrich receives a unstruct_event with schema `iglu:myvendor/myschema/jsonschema/1-0-0`
- The Iglu Server tells us this schema is superseded by `iglu:myvendor/myschema/jsonschema/1-0-1`
- ...so Enrich validates against the 1-0-1 schema.

My questions are...

1. What is in the `$self` field of the unstruct_event emitted by enrich.  Is the the `1-0-0` schema key or the `1-0-1` schema key?
2. Please give an example of what the `superseding_info` context will look like for this case.

I think if you share this information then we can better comment on whether the field names of this new schema are appropriate.

**Comment by spenes** [comment]
1) It will contain `1-0-1` schema key.
2) It will look like this:
```
{
  "schema":"iglu:com.snowplowanalytics.iglu/superseding_info/jsonschema/1-0-0",
  "data":{
    "originalSchema":"iglu:myvendor/myschema/jsonschema/1-0-0",
    "supersededBy":"1-0-1"
   }
}
```

**Comment by spenes** [comment]
Schema name and field are updated to make them more descriptive.

@istreeter Could you give it one more look, please ?

**Comment by spenes** [comment]
Closing and moved schema commits to R141 release (https://github.com/snowplow/iglu-central/pull/1258)

**Pull request closed without merging**
