### PR TITLE
Sauna configs: append schema version to generated class names

### LINKED ISSUE #511: Sauna configs: append schema version to generated class names
e.g. `AmazonDynamodbConfig` -> `AmazonDynamodbConfig_1_0_0`.

See also: #505.

### PR DESCRIPTION
**Pull request by rzats**
Closes #511. I've also applied these changes to the pending config PRs (#498, #501).

### CODE REVIEW

**Comment by rzats** [comment]
The Sauna counterpart of this: https://github.com/snowplow/sauna/pull/74/commits/328f11a62d423f6191d221bfb85f43398f243215

**Comment by alexanderdean** [comment]
Commit and individual ticket in R76 please! This is so we can keep a very close eye on schema mutations in the CHANGELOG...

**Comment by alexanderdean** [comment]
Pushing back given that the requested changes haven't been made in time.

**Comment by rzats** [comment]
This is now split into #589 #590 #591 #592 #593 #594 #595 - closing...

**Comment by alexanderdean** [comment]
Descheduling too

**Pull request closed without merging**
