### PR TITLE
Fixes JSONPaths, SQL encoding for org.w3/PerformanceTiming

### PR DESCRIPTION
**Pull request by bernardosrulzon**
The JSONPaths file is slightly out of sync with the table DDL, which results in  `connectStart` being loaded as `secureConnectionStart`.

I've taken the opportunity to update column encodings to ZSTD

### CODE REVIEW

**Comment by alexanderdean** [comment]
Ouch! Great catch @bernardosrulzon

**Comment by snowplowcla** [comment]
@bernardosrulzon has signed the Individual Contributor License Agreement. Thanks so much

**Comment by alexanderdean** [comment]
Hey @chuwy - how will this JSON Paths patch interact with #726 - will it overwrite in place (i.e. fix) the JSON Paths file in all region buckets?

**Comment by chuwy** [comment]
Hey @alexanderdean, 

> will it overwrite in place (i.e. fix) the JSON Paths file in all region buckets?

Yes exactly this is what will happen.

**Comment by chuwy** [comment]
Closing in favor of https://github.com/snowplow/iglu-central/pull/860. Thanks!

**Pull request closed without merging**
