### PR TITLE
Add com.snowplowanalytics.snowplow.ecommerce/snowplow_ecommerce_action/jsonschema/1-0-2

### PR DESCRIPTION
**Pull request by igneel64**
Add `transaction_error` as a new action to be paired with #1297

### CODE REVIEW

**Review by matus-tomlein — APPROVED** [review]
LGTM

**Review by rlh1994 — APPROVED** [review]

**Comment by igneel64** [comment]
Will try to add into #1258

**Comment by igneel64** [comment]
@istreeter In this PR the max enum goes from 16 to 17. Does this still pose an issue with https://github.com/snowplow/snowplow-rdb-loader/issues/1158 ?

**Comment by igneel64** [comment]
Changed to `trns_error` to avoid this :)

**Comment by igneel64** [comment]
Added in:
#1305

**Pull request closed without merging**
